trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- checkout: self

- task: Maven@4
  displayName: 'Build and test with maven'
  inputs:
  mavenPomFile: 'pom.xml'
  goals: 'clean verify'
  javahomeOptin: 'JDKVersion'
  jdkversionOption: '1.21'
  mavenversionOption:'default'




