trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- checkout: self

- task: Maven@4
  displayName: 'Build and test with maven'
  inputs:
    mavenPOMFile: 'pom.xml'
    goals: 'clean verify'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.21'
    mavenVersionOption: 'Default'

- task: PublishPipelineArtifact@1
displayName: 'publish JAR artifact'
inputs:
  targetpath: '$ (system DefaultWorkingDirectory)/target'
  artifact: 'petclinic-jar'




