trigger:
- main

pool:
  vmImage: ubuntu-latest
  
jobs:
- job: Build
  displayName: Build and Publish JAR
  steps:
  - checkout: self

  - task: Maven@4
    displayName: 'Build and test with maven'
    inputs:
      mavenPOMFile: 'pom.xml'
      goals: 'clean verify'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.21'
      mavenVersionOption: 'Default'

  - task: PublishPipelineArtifact@1
    displayName: 'publish JAR artifact'
    inputs:
      targetpath: '$(system.DefaultWorkingDirectory)/target/spring-petclinic-4.0.0-SNAPSHOT.jar'
      artifact: 'petclinic-jar'
      publishLocation: 'pipeline' 

- job: DockerBuild
  displayName: Download JAR
  dependsOn: Build

  steps:
  - task: DownloadPipelineArtifact@2
    displayName: 'Download JAR artifact'
    inputs:
      buildType: 'current'
      artifactName: 'petclinic-jar'
      targetPath: '$(Pipeline.Workspace)/petclinic-jar'

  - script: cp $(Pipeline.Workspace)/petclinic-jar/spring-petclinic-4.0.0-SNAPSHOT.jar $(Build.SourcesDirectory)/
    displayName: 'Cpyy JAR t Docker build context'
  - script: docker build -t petclinic:latest .
    displayName: 'Build Docker image'

  - task: Docker@2  
    displayName: 'Push Docker image to ACR' 
    inputs:
      command: push 
      containerRegistry: 'Petclinic-256'
      repository: 'Petclinic'
      tags: |
        latest




